version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/rare
    overwrite: yes

permissions:
  - object: /home/ubuntu/rare
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: root
