version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/rare
    overwrite: yes

permissions:
  - object: /home/ubuntu/rare
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: beforeInstall.sh
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root