version: "3"
services:
  db:
    image: mysql:5.7.29
    container_name: rare-local-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rare
      MYSQL_ROOT_PASSWORD: rare
      MYSQL_ROOT_HOST: '%'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./dump/:/docker-entrypoint-initdb.d/"
