spring:
  profiles:
    active: local

---
# spring, datasource
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rare
    username: root
    password: rare
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# logging
logging:
  level:
    web: debug
    com.codesquad.rare: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

# actuator
management:
  endpoints:
    web:
      exposure:
        exclude: env,beans
        include: "*"
      base-path: '/system/actuator'
  endpoint:
    health:
      show-details: always
server:
  port: 8090

---
# spring, datasource
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/rare
    username: ${DB_USER}
    password: ${DB_PW}
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    web: debug
    com.codesquad.rare: debug

# actuator
management:
  endpoints:
    web:
      exposure:
        exclude: env,beans
        include: "*"
      base-path: ${ACTUATOR}
  endpoint:
    health:
      show-details: always

cloud:
  aws:
    credentials:
      accessKey: ${IAM_ACCESS_KEY}
      secretKey: ${IAM_SECRET_KEY}
    s3:
      bucket-user: ${BUCKET_USER_PATH}
      bucket-post: ${BUCKET_POST_PATH}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false