spring:
  profiles:
    active: local

---
# spring, datasource
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rare
    username: root
    password: rare
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# logging
logging:
  level:
    web: debug
    com.codesquad.rare: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

# actuator
management:
  endpoints:
    web:
      exposure:
        exclude: env,beans
        include: "*"
      base-path: '/system/actuator'
  endpoint:
    health:
      show-details: always

---
# spring, datasource
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/rare
    username: ${DB_USER}
    password: ${DB_PW}
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    web: debug
    com.codesquad.rare: debug

# actuator
management:
  endpoints:
    web:
      exposure:
        exclude: env,beans
        include: "*"
      base-path: ${ACTUATOR}
  endpoint:
    health:
      show-details: always

---
# spring, datasource
spring:
  profiles: fix
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# logging
logging:
  level:
    web: debug
    com.codesquad.rare: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

# actuator
management:
  endpoints:
    web:
      exposure:
        exclude: env,beans
        include: "*"
      base-path: '/system/actuator'
  endpoint:
    health:
      show-details: always
